<?php

$loginPassword = 'Facepunch'; // This is the plain-text password, change this to whatever you want to use as a password.
$md5LoginPassword = md5($loginPassword); // If you want to store your password in MD5 form only, delete the above line and replace "md5($loginPassword)" with your MD5 hash.
$phpSessionName = 'php-admin-login'; // Name of the PHP Session used to store the MD5 hashed password. You can change this to avoid interference with other websites that may use this same login code.

$loginPasswordPOST = $_POST["password"];
session_start(); $md5LoginPasswordSession = $_SESSION[$phpSessionName];

function logIn() {
global $loginPassword;
global $md5LoginPassword;
global $loginPasswordPOST;
global $md5LoginPasswordSession;
global $phpSessionName;
$md5LoginPasswordPOST = md5($loginPasswordPOST);
if ($md5LoginPasswordPOST == $md5LoginPassword) {session_start(); $_SESSION[$phpSessionName]=$md5LoginPasswordPOST; loginSuccess(); };
if ($md5LoginPasswordSession !== $md5LoginPassword) {loginFailed("invalid"); };
if ($md5LoginPasswordSession == $md5LoginPassword) {loginSuccess(); };
};

function loginErrorMessage() {
	$loginErrorReason = $_GET['failed'];
	if ($loginErrorReason == 'denied') {echo 'Access is denied or your session has expired. Please enter your password.'; }; // Login Error Explanation if a user tries to access a password protected page when they aren't logged in.
	if ($loginErrorReason == 'invalid') {echo 'The password you entered is incorrect. Please try again.'; }; // Login Error Explanation if the user didn't enter the correct password.
};

function loginFailed($reason) {
	header("HTTP/1.1 301 Moved Permanently"); 
	header("Location: login.php?failed={$reason}"); // User is redirected back to the login page with a corresponding error message (generated by loginErrorMessage() above) as to why their login failed.
	exit;
};
	
function loginSuccess() {
	header("HTTP/1.1 301 Moved Permanently"); 
	header("Location: admin.php"); // Where the user is redirected to when they log in.
	exit;
};
	
function logOut() {
	global $phpSessionName;
	session_start();
	unset($_SESSION[$phpSessionName]);
	session_destroy();
	header("HTTP/1.1 301 Moved Permanently"); 
	header("Location: login.php"); // Where the user is redirected to when they log out.
	exit;
};
	
?>
